# Generated by Django 4.1.4 on 2022-12-10 01:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[project.models.LettersOnlyValidator])),
                ('last_name', models.CharField(max_length=25, validators=[project.models.LettersOnlyValidator])),
                ('age', models.IntegerField(default=18, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(13)])),
                ('default_city', models.CharField(default='New York', max_length=25)),
                ('theme', models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark'), ('Default', 'Default')], default='Default', max_length=7)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('persons', models.ManyToManyField(related_name='Cities', to='project.person')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
    ]
